# Generated by Django 4.1 on 2022-08-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_date', models.DateField()),
                ('sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('train_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tuijian_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
