# Generated by Django 4.1 on 2022-08-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0002_alter_shopday_sales_alter_shopday_train_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopday',
            name='shop_id',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='shopday',
            name='shop_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopday',
            name='shop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
