# Generated by Django 4.1 on 2022-08-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0003_shopday_shop_id_alter_shopday_shop_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopday',
            name='sales',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='shopday',
            name='train_cost',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='shopday',
            name='tuijian_cost',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
