# Generated by Django 4.1 on 2022-08-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0005_alter_shopday_shop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopday',
            name='train_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='shopday',
            name='tuijian_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
