# Generated by Django 4.1 on 2022-08-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0006_alter_shopday_train_cost_alter_shopday_tuijian_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopday',
            name='train_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopday',
            name='tuijian_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
